### ISSUE TITLE
Can't install aurora-cli via npm 7.*

### ISSUE THREAD

**Issue by strokovok** [aurora-is-near/aurora-cli#10]
Attempts to run `npm install -g aurora-is-near/aurora-cli` with and without `sudo` are not successful if using nodejs15/16+npm7.*
It only works when using nodejs14+npm6.*

Is `aurora-cli` supposed to work with 7.* npm versions?

**Comment by spilin** [comment]
This repository is no longer maintained. Please visit [Aurora CLI](https://github.com/aurora-is-near/aurora-cli-rs) for latest release of Aurora CLI. Feel free to submit your issues/proposals there.
