### ISSUE TITLE
Reimplement and fix `aurora dump-storage`

### ISSUE THREAD

**Issue by artob** [aurora-is-near/aurora-cli#2]
```console
% aurora dump-storage
...
TypedError: [-32000] Server error: State of contract aurora is too large to be viewed
```

**Comment by spilin** [comment]
This repository is no longer maintained. Please visit [Aurora CLI](https://github.com/aurora-is-near/aurora-cli-rs) for latest release of Aurora CLI. Feel free to submit your issues/proposals there.
