### ISSUE TITLE
Using Rainbow bridge programatically

### ISSUE THREAD

**Issue by cenwadike** [aurora-is-near/aurora-cli#20]
My understanding of Rainbow Bridge is that `eth token` in `solidity` are _bridged_ as `near-wrapped-eth-token` written in `rust`.
Is there a way to programaticlly `call` the `near-wrapped-eth-token` `interfaces/functions` from a 3rd party `solidity contract` running on **Aurora**.

**Comment by spilin** [comment]
This repository is no longer maintained. Please visit [Aurora CLI](https://github.com/aurora-is-near/aurora-cli-rs) for latest release of Aurora CLI. Feel free to submit your issues/proposals there.
